### ISSUE TITLE
After clicking "Deploy to Heroku", requests for admin CSS and JS results in HTTP 503 errors

### ISSUE THREAD

**Issue by craiga** [torchbox/wagtaildemo#101]
After clicking "Deploy to Heroku" from this GitHub project, the site appears to load normally, but listing admin fails to load any of its JS or CSS.

Looking in the dev console, it looks like all requests for admin CSS and JS result in HTTP 503 errors.

**Comment by maikhoepfel** [comment]
I just did the deploy to Heroku, and it fails with a 400 "Disallowed host". Sounds like the button still needs some work.

**Comment by gasman** [comment]
Confirmed here. This happens because the current releases of Django as of 1st November (1.8.16, 1.9.11, 1.10.3 and above) enforce `ALLOWED_HOSTS` even when `DEBUG` is true:

https://docs.djangoproject.com/en/1.10/releases/1.10.3/#dns-rebinding-vulnerability-when-debug-true

Since everyone's hostname on Heroku is different, there's no meaningful hostname we can put in `ALLOWED_HOSTS`. However, I reckon it would be appropriate to set `ALLOWED_HOSTS = ['*']` in this case: it means that we're bypassing the security features that Django is providing by enforcing `ALLOWED_HOSTS` in the first place, but anyone doing anything security-critical with wagtaildemo on Heroku ought to be reading and adjusting the settings files appropriately (if they don't, they're already falling foul of [the non-secret `SECRET_KEY`](https://github.com/torchbox/wagtaildemo/blob/master/wagtaildemo/settings/base.py#L92-L96)).

**Comment by maikhoepfel** [comment]
I agree about setting `'*'`. FWIW, Heroku's router prevents hostnames not belonging to the app anyway, so this should be pretty safe.

**Comment by gasman** [comment]
OK, I think this is sorted now: have added `ALLOWED_HOSTS = ['*']` in ede7ee09d9b33f1e9429ddc6549141338f51cce5, and fixed the issue with serving admin JS/CSS by upgrading whitenoise to >=3.1 in 5992b9e49a403fb5e7f716846f44c800b08c75d3.

**Comment by maikhoepfel** [comment]
Lovely, thanks Matt!
