### ISSUE TITLE
Document libjpeg/zlib etc as dependencies of PIL; add a runserver check for their presence

### ISSUE THREAD

**Issue by btipling** [torchbox/wagtaildemo#12]
Is this expected?

![2014-02-14 at 5 39 am 2x](https://f.cloud.github.com/assets/249641/2171147/a108d4b6-957d-11e3-8eaa-6f6efb733219.png)

**Comment by BertrandBordage** [comment]
I can’t reproduce this bug.  Maybe it’s a file/folder permission issue?

**Comment by gasman** [comment]
It sounds like this is universally caused by missing dependencies of PIL. Have updated the issue title to address the fixes that @btipling proposes.

**Comment by BertrandBordage** [comment]
So this could be closed in favor of #7 if I understand well.

**Comment by gasman** [comment]
http://docs.wagtail.io/en/v1.0/getting_started/index.html now covers the fact that Pillow requires additional libraries (and this document is the current recommended route for new users, rather than wagtaildemo). Adding a runserver check is covered in https://github.com/torchbox/wagtail/issues/1644.
