### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by mjdavies** [torchbox/wagtaildemo#34]
Morning all

Whats the chances of you sticking some tests into this demo app for others to build upon as they develop it?

I can see you've got great coverage of wagtail itself, so it may not be such a big deal to start sticking some into this app?

**Comment by davecranwell** [comment]
Hi @mjdavies,

We've recently changed our approach to the wagtaildemo site due to the maintenance costs associated with it. 

Its no longer intended to be built upon to create your own sites and we've updated the README to explain this. It's purely there to illustrate - crudely in some cases - the possibilities in Wagtail. As such I don't think it would be particularly worthwhile adding unit tests. I'm therefore closing this.
